name: Rust Release

on:
  push:
    tags:
      - rust-v*

permissions:
  contents: write

jobs:
  rust-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish -p unicode-intervals
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Extract version
        run: echo "version=${GITHUB_REF#refs/tags/rust-v}" >> "$GITHUB_ENV"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: false
          draft: true
          name: "[Rust] Release ${{ env.version }}"
